---
title: 'England Blanket Bog Model: run models'
output:
  html_notebook: default
---

model run = `r Sys.time()`

## Packages 
```{r}
library(raster)
library(rgdal)

library(caret)
library(parallel)
library(doParallel)
```

## Load data
```{r}
load(file = "../data/input.data.rds")
```

## Start Parallel Processing

```{r}
detectCores()
getDoParWorkers()
cl <- makeCluster(detectCores()-1)
registerDoParallel(cl)
getDoParName()
getDoParWorkers()
#registerDoSEQ() # to stop parallel processing
```

#### Make training and test set

```{r}
library(caret)
set.seed(123)
inTrain <- createDataPartition(y = input.data$bbog, 
                               p = .75, # The percentage of data in the training set
                               list = FALSE) # The format of the results

training <- input.data[inTrain,]
testing <- input.data[-inTrain,]
nrow(training); nrow(testing)
table(training$bbog)
table(testing$bbog)
```

#### run model
Need the latest version of caret from github to avoid known bug.
```{r}
#run with moorland line but drop some rainfall varialbes
training8a <- training[!(names(training) %in% c("surf", "rain_daily", "raindays_1mm"))]
M.rf.8a <- train(bbog ~ .,
                data= training8a, 
                method = "rf")
save(M.rf.8a, file = "../data/models/Mrf8a.rds")

#run without moorland line
training8b <- training[!(names(training) %in% c("moorline", "surf", "rain_daily", "raindays_1mm"))] 

M.rf.8b <- train(bbog ~ .,
                data= training8b, 
                method = "rf")
save(M.rf.8b, file = "../data/models/Mrf8b.rds")

#run with moorland line and include rainfall varialbes
training8c <- training[!(names(training) %in% c("surf"))]
M.rf.8c <- train(bbog ~ .,
                data= training8c, 
                method = "rf")
save(M.rf.8c, file = "../data/models/Mrf8c.rds")

#run without moorland line and include rainfall varialbes
training8d <- training[!(names(training) %in% c("moorline", "surf"))] 

M.rf.8d <- train(bbog ~ .,
                data= training8d, 
                method = "rf")
save(M.rf.8d, file = "../data/models/Mrf8d.rds")



M.rf.8b; M.rf.8b; M.rf.8c; M.rf.8d
```



```{r}
plot(varImp(object= M.rf.8a), main= "RF - Variable Importance")
plot(varImp(object= M.rf.8b), main= "RF - Variable Importance")
plot(varImp(object= M.rf.8c), main= "RF - Variable Importance")
plot(varImp(object= M.rf.8d), main= "RF - Variable Importance")
```

### Predict from model

```{r}
#Predictions
predictions8a <- caret::predict.train(object = M.rf.8a, newdata = testing, type="prob", index = "present")
predictions8b <- caret::predict.train(object = M.rf.8b, newdata = testing, type="prob", index = "present")
predictions8c <- caret::predict.train(object = M.rf.8c, newdata = testing, type="prob", index = "present")
predictions8d <- caret::predict.train(object = M.rf.8d, newdata = testing, type="prob", index = "present")
```


### run final models

```{r}
input.data.8a <- input.data[names(input.data) %in% names(training8a)] 
M.rf.8a.final <- train(bbog ~ .,
                data = input.data.8a,
                method = "rf")
save(M.rf.8a.final, file = "../data/models/Mrf8afinal.rds")

input.data.8b <- input.data[names(input.data) %in% names(training8b)] 
M.rf.8b.final <- train(bbog ~ .,
                data = input.data.8b,
                method = "rf")
save(M.rf.8b.final, file = "../data/models/Mrf8bfinal.rds")

input.data.8c <- input.data[names(input.data) %in% names(training8c)] 
M.rf.8c.final <- train(bbog ~ .,
                data = input.data.8c,
                method = "rf")
save(M.rf.8c.final, file = "../data/models/Mrf8cfinal.rds")

input.data.8d <- input.data[names(input.data) %in% names(training8d)] 
M.rf.8d.final <- train(bbog ~ .,
                data = input.data.8d,
                method = "rf")
save(M.rf.8d.final, file = "../data/models/Mrf8dfinal.rds")

M.rf.8a.final; M.rf.8b.final; M.rf.8c.final; M.rf.8d.final
```


